global using System.ComponentModel.DataAnnotations;
global using MusicClub.Cms.Blazor.Interfaces;
global using MusicClub.Dto.Results;
global using MusicClub.Dto.Requests;
global using MusicClub.Dto.Attributes;
global using MusicClub.Dto.Filters.Requests;
global using MusicClub.Dto.Filters.Results;
global using System;
global using MusicClub.Cms.Blazor.Models.FormModels.Data;