using Microsoft.CodeAnalysis;

namespace MusicClub.SourceGenerators
{
    [Generator]
    public class FilterResultGenerator : ISourceGenerator
    {
        public void Execute(GeneratorExecutionContext context)
        {
            // Find the main method
            var mainMethod = context.Compilation.GetEntryPoint(context.CancellationToken);

            // Build up the source code
            string source = 
            $@"// <auto-generated/>
            using System;

            namespace {mainMethod.ContainingNamespace.ToDisplayString()}
            {{
                public static partial class {mainMethod.ContainingType.Name}
                {{
                    static partial void HelloFrom(string name)
                    {{
                        Console.WriteLine($""Generator says: Koekoek from '{{name}}'"");
                        Console.ReadKey();
                    }}

                }}
            }}
            ";

            var typeName = mainMethod.ContainingType.Name;

            // Add the source code to the compilation
            context.AddSource($"{typeName}.g.cs", source);   
        }

        public void Initialize(GeneratorInitializationContext context) { }
    }
}
